import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/TopNav";
import Navber from "@/components/Navber";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hosting",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="custom-gradient  ">
          <div>
            <TopNav />
            <Navber/>
            
          </div>
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
